name: Trigger Target Repository Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  trigger-target-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger target repository workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.TOKEN }}
        repository: roohmeiy/target-repo
        event-type: source-updated

