
name: Sync Repositories

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.TOKEN }}

    - run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - run: |
        git rm .github/workflows/sync.yml
        git commit -m "Remove sync workflow from target sync" || true

    - run: git remote add target https://${{ secrets.TOKEN }}@github.com/roohmeiy/target-repo.git

    - run: git fetch target

    - run: |
        git checkout main
        git push target main:main --force-with-lease

    - run: |
        if git show-ref --verify --quiet refs/heads/develop; then
          git checkout develop
          git push target develop:develop --force-with-lease
        fi

    - run: git push target --tags
