name: Sync to Source

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [sync-from-source]

jobs:
  sync-to-source:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.TOKEN }}

    - run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - run: git remote add source https://${{ secrets.TOKEN }}@github.com/roohmeiy/source-repo.git

    - run: git fetch source

    - run: |
        git checkout main
        git push source main:main --force-with-lease

    - run: |
        if git show-ref --verify --quiet refs/heads/develop; then
          git checkout develop
          git push source develop:develop --force-with-lease
        fi

    - run: git push source --tags

  sync-from-source:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.TOKEN }}

    - run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - run: git remote add source https://${{ secrets.TOKEN }}@github.com/roohmeiy/source-repo.git

    - run: git fetch source

    - run: |
        git reset --hard source/main
        git push origin main --force-with-lease

    - run: |
        if git show-ref --verify --quiet refs/remotes/source/develop; then
          git checkout -B develop source/develop
          git push origin develop --force-with-lease
        fi
